import Config

# Configure the database for development
config :kuma_san_kanji, KumaSanKanji.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "kuma_san_kanji_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Token signing secret for AshAuthentication
config :kuma_san_kanji, :token_signing_secret, "dev-secret-key-this-should-be-changed-in-production"

# Auth0 configuration for development
config :kuma_san_kanji, :auth0,
  client_id: System.get_env("AUTH0_CLIENT_ID") || "your-auth0-client-id",
  client_secret: System.get_env("AUTH0_CLIENT_SECRET") || "your-auth0-client-secret", 
  base_url: System.get_env("AUTH0_DOMAIN") || "https://your-domain.auth0.com",
  redirect_uri: System.get_env("AUTH0_REDIRECT_URI") || "http://localhost:4000/auth/user/auth0/callback"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :kuma_san_kanji, KumaSanKanjiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "bQsNOQYbw3Ju7J7yYn7BttLahgBuesIKB1pQ60sOksrH8IWNGlCGwnhakvLlxXFD",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:kuma_san_kanji, ~w(--sourcemap=inline --watch)]},
    npm: ["run", "watch", cd: Path.expand("../assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :kuma_san_kanji, KumaSanKanjiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/kuma_san_kanji_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :kuma_san_kanji, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Import secret configuration if it exists (for local overrides)
if File.exists?(Path.join(__DIR__, "dev.secrets.exs")) do
  import_config "dev.secrets.exs"
end