defmodule KumaSanKanji.Repo.Migrations.CreateInitialTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:email, :citext, null: false)
      add(:hashed_password, :text, null: false)
      add(:username, :text, null: false)
      add(:joined_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))
    end

    create(unique_index(:users, [:email], name: "users_unique_email_index"))

    create table(:user_kanji_progress, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:next_review_date, :utc_datetime, null: false)
      add(:interval, :bigint, null: false, default: 1)
      add(:ease_factor, :decimal, null: false, default: "2.5")
      add(:repetitions, :bigint, null: false, default: 0)
      add(:last_result, :text)
      add(:first_reviewed_at, :utc_datetime)
      add(:last_reviewed_at, :utc_datetime)
      add(:total_reviews, :bigint, null: false, default: 0)
      add(:correct_reviews, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "user_kanji_progress_user_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:kanji_id, :uuid, null: false)
    end

    create table(:thematic_groups, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:color_code, :text)
      add(:icon_name, :text)
      add(:order_index, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :parent_id,
        references(:thematic_groups,
          column: :id,
          name: "thematic_groups_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create table(:kanjis, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:user_kanji_progress) do
      modify(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "user_kanji_progress_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(
      unique_index(:user_kanji_progress, [:user_id, :kanji_id],
        name: "user_kanji_progress_unique_user_kanji_index"
      )
    )

    alter table(:kanjis) do
      add(:character, :text, null: false)
      add(:grade, :bigint)
      add(:stroke_count, :bigint)
      add(:jlpt_level, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:kanji_usage_examples, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kanji_id, :uuid, null: false)
      add(:context, :text, null: false)
      add(:romaji, :text)
      add(:translation, :text)
      add(:difficulty_level, :bigint)
      add(:source, :text)
      add(:notes, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:kanji_thematic_groups, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kanji_id, :uuid, null: false)
      add(:relevance_score, :float, default: 1.0)
      add(:notes, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :thematic_group_id,
        references(:thematic_groups,
          column: :id,
          name: "kanji_thematic_groups_thematic_group_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create table(:kanji_pronunciations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:value, :text, null: false)
      add(:type, :text, null: false)
      add(:romaji, :text)

      add(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "kanji_pronunciations_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:kanji_pronunciations, [:kanji_id, :value, :type],
        name: "kanji_pronunciations_unique_pronunciation_per_kanji_index"
      )
    )

    create table(:kanji_meanings, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:value, :text, null: false)
      add(:language, :text, default: "en")
      add(:is_primary, :boolean, default: false)

      add(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "kanji_meanings_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:kanji_meanings, [:kanji_id, :value, :language],
        name: "kanji_meanings_unique_meaning_per_kanji_index"
      )
    )

    create table(:kanji_learning_meta, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kanji_id, :uuid, null: false)
      add(:difficulty_score, :float)
      add(:prerequisites, {:array, :text})
      add(:learning_tips, :text)
      add(:common_mistakes, :text)
      add(:mnemonic_hints, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:educational_context_id, :uuid)
    end

    create table(:kanji_example_sentences, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:japanese, :text, null: false)
      add(:translation, :text, null: false)
      add(:language, :text, default: "en")

      add(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "kanji_example_sentences_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:kanji_example_sentences, [:kanji_id, :japanese, :translation, :language],
        name: "kanji_example_sentences_unique_sentence_per_kanji_index"
      )
    )

    create table(:educational_contexts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:kanji_learning_meta) do
      modify(
        :educational_context_id,
        references(:educational_contexts,
          column: :id,
          name: "kanji_learning_meta_educational_context_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:educational_contexts) do
      add(:name, :text, null: false)
      add(:description, :text)
      add(:grade_level, :bigint)
      add(:curriculum_area, :text)
      add(:learning_objectives, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:educational_contexts) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:learning_objectives)
      remove(:curriculum_area)
      remove(:grade_level)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:kanji_learning_meta, "kanji_learning_meta_educational_context_id_fkey"))

    alter table(:kanji_learning_meta) do
      modify(:educational_context_id, :uuid)
    end

    drop(table(:educational_contexts))

    drop_if_exists(
      unique_index(:kanji_example_sentences, [:kanji_id, :japanese, :translation, :language],
        name: "kanji_example_sentences_unique_sentence_per_kanji_index"
      )
    )

    drop(constraint(:kanji_example_sentences, "kanji_example_sentences_kanji_id_fkey"))

    drop(table(:kanji_example_sentences))

    drop(table(:kanji_learning_meta))

    drop_if_exists(
      unique_index(:kanji_meanings, [:kanji_id, :value, :language],
        name: "kanji_meanings_unique_meaning_per_kanji_index"
      )
    )

    drop(constraint(:kanji_meanings, "kanji_meanings_kanji_id_fkey"))

    drop(table(:kanji_meanings))

    drop_if_exists(
      unique_index(:kanji_pronunciations, [:kanji_id, :value, :type],
        name: "kanji_pronunciations_unique_pronunciation_per_kanji_index"
      )
    )

    drop(constraint(:kanji_pronunciations, "kanji_pronunciations_kanji_id_fkey"))

    drop(table(:kanji_pronunciations))

    drop(constraint(:kanji_thematic_groups, "kanji_thematic_groups_thematic_group_id_fkey"))

    drop(table(:kanji_thematic_groups))

    drop(table(:kanji_usage_examples))

    alter table(:kanjis) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:jlpt_level)
      remove(:stroke_count)
      remove(:grade)
      remove(:character)
    end

    drop_if_exists(
      unique_index(:user_kanji_progress, [:user_id, :kanji_id],
        name: "user_kanji_progress_unique_user_kanji_index"
      )
    )

    drop(constraint(:user_kanji_progress, "user_kanji_progress_kanji_id_fkey"))

    alter table(:user_kanji_progress) do
      modify(:kanji_id, :uuid)
    end

    drop(table(:kanjis))

    drop(constraint(:thematic_groups, "thematic_groups_parent_id_fkey"))

    drop(table(:thematic_groups))

    drop(constraint(:user_kanji_progress, "user_kanji_progress_user_id_fkey"))

    drop(table(:user_kanji_progress))

    drop_if_exists(unique_index(:users, [:email], name: "users_unique_email_index"))

    drop(table(:users))
  end
end
