defmodule KumaSanKanji.Repo.Migrations.AddRadicalsSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
  # User & token adjustments skipped: already applied in prior migrations / removed intentionally.

    create table(:radicals, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:glyph, :text, null: false)
      add(:kangxi_index, :bigint, null: false)
      add(:stroke_count, :bigint, null: false)
      add(:meaning, :text, null: false)
      add(:japanese_name, :text)
      add(:alt_forms, {:array, :text}, default: [])
      add(:sample_kanji, {:array, :text}, default: [])
      add(:notes, :text)
      add(:mnemonic, :text)
      add(:frequency_rank, :bigint)
      add(:high_yield, :boolean, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:radicals, [:glyph], name: "radicals_unique_glyph_index"))

    create(unique_index(:radicals, [:kangxi_index], name: "radicals_unique_kangxi_index_index"))

    alter table(:kanjis) do
      add(
        :radical_id,
        references(:radicals,
          column: :id,
          name: "kanjis_radical_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
  drop(constraint(:kanjis, "kanjis_radical_id_fkey"))

    alter table(:kanjis) do
      remove(:radical_id)
    end

    drop_if_exists(
      unique_index(:radicals, [:kangxi_index], name: "radicals_unique_kangxi_index_index")
    )

    drop_if_exists(unique_index(:radicals, [:glyph], name: "radicals_unique_glyph_index"))

  drop(table(:radicals))
  # Skipping token & user reversal as they were not applied here.
  end
end
