defmodule KumaSanKanji.Repo.Migrations.UpdateKanjiResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:kanji_usage_examples) do
      modify(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "kanji_usage_examples_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(index(:kanji_usage_examples, [:kanji_id]))

    create(
      unique_index(:kanji_thematic_groups, [:kanji_id, :thematic_group_id],
        name: "kanji_thematic_groups_unique_kanji_in_group_index"
      )
    )

    alter table(:kanji_learning_meta) do
      modify(
        :kanji_id,
        references(:kanjis,
          column: :id,
          name: "kanji_learning_meta_kanji_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    create(index(:kanji_learning_meta, [:kanji_id]))
  end

  def down do
    drop_if_exists(index(:kanji_learning_meta, [:kanji_id]))

    drop(constraint(:kanji_learning_meta, "kanji_learning_meta_kanji_id_fkey"))

    alter table(:kanji_learning_meta) do
      modify(:kanji_id, :uuid)
    end

    drop_if_exists(
      unique_index(:kanji_thematic_groups, [:kanji_id, :thematic_group_id],
        name: "kanji_thematic_groups_unique_kanji_in_group_index"
      )
    )

    drop_if_exists(index(:kanji_usage_examples, [:kanji_id]))

    drop(constraint(:kanji_usage_examples, "kanji_usage_examples_kanji_id_fkey"))

    alter table(:kanji_usage_examples) do
      modify(:kanji_id, :uuid)
    end
  end
end
