defmodule KumaSanKanji.Repo.Migrations.AddNotesToProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_kanji_progress) do
      add(:notes, :text)
    end
  end

  def down do
    alter table(:user_kanji_progress) do
      remove(:notes)
    end
  end
end
