defmodule KumaSanKanji.Repo.Migrations.AddSettingsToUser do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add(:theme, :text, default: "cupcake")
      add(:marketing_emails, :boolean, default: false)
      add(:study_reminders, :boolean, default: true)
    end
  end

  def down do
    alter table(:users) do
      remove(:study_reminders)
      remove(:marketing_emails)
      remove(:theme)
    end
  end
end
