defmodule KumaSanKanji.Repo.Migrations.RemoveRomaji do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:kanji_usage_examples) do
      remove(:romaji)
    end
  end

  def down do
    alter table(:kanji_usage_examples) do
      add(:romaji, :text)
    end
  end
end
